server.port=8080

app.url=http://localhost:${server.port}

spring.profiles.active=test

file.uploadPath=images/

file.directoryMapping=D:/develop/java/springBoot_learning/XeChat/xechat/

file.staticAccessPath=/**

file.accessAddress=${app.url}/${file.uploadPath}

spring.servlet.multipart.maxFileSize=30MB
spring.servlet.multipart.maxRequestSize=30MB
chatrecord.path=D:/develop/java/springBoot_learning/XeChat/xechat/chatrecord/
chatrecord.accessAddress=${app.url}/chatrecord/
chatrecord.password=c85715fec7827f3b388af185b8e7db77
restTemplate.threadSize=20
restTemplate.waitingTime=500
restTemplate.connectTimeOut=10000
restTemplate.readTimeOut=10000
turing.apiUrl=http://openapi.tuling123.com/openapi/api/v2
turing.apiKey=
spring.threads.virtual.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/xechat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true